name: flatland-baseline-cpu-env
dependencies:
    - conda-build
    - python=3.7
    - libgcc
    - pip
    - cairo
    - pip:
        - flatland-rl==2.2.1
        - CairoSVG==2.4.2
        - pyhumps==1.3.1
        - gputil==1.4.0
        - pyhumps==1.3.1
        - wandb==0.9.2
        - ray[rllib]==0.8.5
        - tensorflow==2.1.0
